# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@babel/runtime-7.26.9" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.26.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.26.9.tgz";
        sha512 = "aA63XwOkcl4xxQa3HjPMqOP6LiK0ZDv3mUPYEFXkpHbaFjtGggE1A61FjFzJnB+p7/oy2gA8E+rcBNl/zC1tMg==";
      };
    };
    "@jimp/bmp-0.16.13" = {
      name = "_at_jimp_slash_bmp";
      packageName = "@jimp/bmp";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/bmp/-/bmp-0.16.13.tgz";
        sha512 = "9edAxu7N2FX7vzkdl5Jo1BbACfycUtBQX+XBMcHA2bk62P8R0otgkHg798frgAk/WxQIzwxqOH6wMiCwrlAzdQ==";
      };
    };
    "@jimp/core-0.16.13" = {
      name = "_at_jimp_slash_core";
      packageName = "@jimp/core";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/core/-/core-0.16.13.tgz";
        sha512 = "qXpA1tzTnlkTku9yqtuRtS/wVntvE6f3m3GNxdTdtmc+O+Wcg9Xo2ABPMh7Nc0AHbMKzwvwgB2JnjZmlmJEObg==";
      };
    };
    "@jimp/custom-0.16.13" = {
      name = "_at_jimp_slash_custom";
      packageName = "@jimp/custom";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/custom/-/custom-0.16.13.tgz";
        sha512 = "LTATglVUPGkPf15zX1wTMlZ0+AU7cGEGF6ekVF1crA8eHUWsGjrYTB+Ht4E3HTrCok8weQG+K01rJndCp/l4XA==";
      };
    };
    "@jimp/gif-0.16.13" = {
      name = "_at_jimp_slash_gif";
      packageName = "@jimp/gif";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/gif/-/gif-0.16.13.tgz";
        sha512 = "yFAMZGv3o+YcjXilMWWwS/bv1iSqykFahFMSO169uVMtfQVfa90kt4/kDwrXNR6Q9i6VHpFiGZMlF2UnHClBvg==";
      };
    };
    "@jimp/jpeg-0.16.13" = {
      name = "_at_jimp_slash_jpeg";
      packageName = "@jimp/jpeg";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/jpeg/-/jpeg-0.16.13.tgz";
        sha512 = "BJHlDxzTlCqP2ThqP8J0eDrbBfod7npWCbJAcfkKqdQuFk0zBPaZ6KKaQKyKxmWJ87Z6ohANZoMKEbtvrwz1AA==";
      };
    };
    "@jimp/plugin-blit-0.16.13" = {
      name = "_at_jimp_slash_plugin-blit";
      packageName = "@jimp/plugin-blit";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-blit/-/plugin-blit-0.16.13.tgz";
        sha512 = "8Z1k96ZFxlhK2bgrY1JNWNwvaBeI/bciLM0yDOni2+aZwfIIiC7Y6PeWHTAvjHNjphz+XCt01WQmOYWCn0ML6g==";
      };
    };
    "@jimp/plugin-blur-0.16.13" = {
      name = "_at_jimp_slash_plugin-blur";
      packageName = "@jimp/plugin-blur";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-blur/-/plugin-blur-0.16.13.tgz";
        sha512 = "PvLrfa8vkej3qinlebyhLpksJgCF5aiysDMSVhOZqwH5nQLLtDE9WYbnsofGw4r0VVpyw3H/ANCIzYTyCtP9Cg==";
      };
    };
    "@jimp/plugin-circle-0.16.13" = {
      name = "_at_jimp_slash_plugin-circle";
      packageName = "@jimp/plugin-circle";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-circle/-/plugin-circle-0.16.13.tgz";
        sha512 = "RNave7EFgZrb5V5EpdvJGAEHMnDAJuwv05hKscNfIYxf0kR3KhViBTDy+MoTnMlIvaKFULfwIgaZWzyhuINMzA==";
      };
    };
    "@jimp/plugin-color-0.16.13" = {
      name = "_at_jimp_slash_plugin-color";
      packageName = "@jimp/plugin-color";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-color/-/plugin-color-0.16.13.tgz";
        sha512 = "xW+9BtEvoIkkH/Wde9ql4nAFbYLkVINhpgAE7VcBUsuuB34WUbcBl/taOuUYQrPEFQJ4jfXiAJZ2H/rvKjCVnQ==";
      };
    };
    "@jimp/plugin-contain-0.16.13" = {
      name = "_at_jimp_slash_plugin-contain";
      packageName = "@jimp/plugin-contain";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-contain/-/plugin-contain-0.16.13.tgz";
        sha512 = "QayTXw4tXMwU6q6acNTQrTTFTXpNRBe+MgTGMDU0lk+23PjlFCO/9sacflelG8lsp7vNHhAxFeHptDMAksEYzg==";
      };
    };
    "@jimp/plugin-cover-0.16.13" = {
      name = "_at_jimp_slash_plugin-cover";
      packageName = "@jimp/plugin-cover";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-cover/-/plugin-cover-0.16.13.tgz";
        sha512 = "BSsP71GTNaqWRcvkbWuIVH+zK7b3TSNebbhDkFK0fVaUTzHuKMS/mgY4hDZIEVt7Rf5FjadAYtsujHN9w0iSYA==";
      };
    };
    "@jimp/plugin-crop-0.16.13" = {
      name = "_at_jimp_slash_plugin-crop";
      packageName = "@jimp/plugin-crop";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-crop/-/plugin-crop-0.16.13.tgz";
        sha512 = "WEl2tPVYwzYL8OKme6Go2xqiWgKsgxlMwyHabdAU4tXaRwOCnOI7v4021gCcBb9zn/oWwguHuKHmK30Fw2Z/PA==";
      };
    };
    "@jimp/plugin-displace-0.16.13" = {
      name = "_at_jimp_slash_plugin-displace";
      packageName = "@jimp/plugin-displace";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-displace/-/plugin-displace-0.16.13.tgz";
        sha512 = "qt9WKq8vWrcjySa9DyQ0x/RBMHQeiVjdVSY1SJsMjssPUf0pS74qorcuAkGi89biN3YoGUgPkpqECnAWnYwgGA==";
      };
    };
    "@jimp/plugin-dither-0.16.13" = {
      name = "_at_jimp_slash_plugin-dither";
      packageName = "@jimp/plugin-dither";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-dither/-/plugin-dither-0.16.13.tgz";
        sha512 = "5/N3yJggbWQTlGZHQYJPmQXEwR52qaXjEzkp1yRBbtdaekXE3BG/suo0fqeoV/csf8ooI78sJzYmIrxNoWVtgQ==";
      };
    };
    "@jimp/plugin-fisheye-0.16.13" = {
      name = "_at_jimp_slash_plugin-fisheye";
      packageName = "@jimp/plugin-fisheye";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-fisheye/-/plugin-fisheye-0.16.13.tgz";
        sha512 = "2rZmTdFbT/cF9lEZIkXCYO0TsT114Q27AX5IAo0Sju6jVQbvIk1dFUTnwLDadTo8wkJlFzGqMQ24Cs8cHWOliA==";
      };
    };
    "@jimp/plugin-flip-0.16.13" = {
      name = "_at_jimp_slash_plugin-flip";
      packageName = "@jimp/plugin-flip";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-flip/-/plugin-flip-0.16.13.tgz";
        sha512 = "EmcgAA74FTc5u7Z+hUO/sRjWwfPPLuOQP5O64x5g4j0T12Bd29IgsYZxoutZo/rb3579+JNa/3wsSEmyVv1EpA==";
      };
    };
    "@jimp/plugin-gaussian-0.16.13" = {
      name = "_at_jimp_slash_plugin-gaussian";
      packageName = "@jimp/plugin-gaussian";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-gaussian/-/plugin-gaussian-0.16.13.tgz";
        sha512 = "A1XKfGQD0iDdIiKqFYi8nZMv4dDVYdxbrmgR7y/CzUHhSYdcmoljLIIsZZM3Iks/Wa353W3vtvkWLuDbQbch1w==";
      };
    };
    "@jimp/plugin-invert-0.16.13" = {
      name = "_at_jimp_slash_plugin-invert";
      packageName = "@jimp/plugin-invert";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-invert/-/plugin-invert-0.16.13.tgz";
        sha512 = "xFMrIn7czEZbdbMzZWuaZFnlLGJDVJ82y5vlsKsXRTG2kcxRsMPXvZRWHV57nSs1YFsNqXSbrC8B98n0E32njQ==";
      };
    };
    "@jimp/plugin-mask-0.16.13" = {
      name = "_at_jimp_slash_plugin-mask";
      packageName = "@jimp/plugin-mask";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-mask/-/plugin-mask-0.16.13.tgz";
        sha512 = "wLRYKVBXql2GAYgt6FkTnCfE+q5NomM7Dlh0oIPGAoMBWDyTx0eYutRK6PlUrRK2yMHuroAJCglICTbxqGzowQ==";
      };
    };
    "@jimp/plugin-normalize-0.16.13" = {
      name = "_at_jimp_slash_plugin-normalize";
      packageName = "@jimp/plugin-normalize";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-normalize/-/plugin-normalize-0.16.13.tgz";
        sha512 = "3tfad0n9soRna4IfW9NzQdQ2Z3ijkmo21DREHbE6CGcMIxOSvfRdSvf1qQPApxjTSo8LTU4MCi/fidx/NZ0GqQ==";
      };
    };
    "@jimp/plugin-print-0.16.13" = {
      name = "_at_jimp_slash_plugin-print";
      packageName = "@jimp/plugin-print";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-print/-/plugin-print-0.16.13.tgz";
        sha512 = "0m6i3p01PGRkGAK9r53hDYrkyMq+tlhLOIbsSTmZyh6HLshUKlTB7eXskF5OpVd5ZUHoltlNc6R+ggvKIzxRFw==";
      };
    };
    "@jimp/plugin-resize-0.16.13" = {
      name = "_at_jimp_slash_plugin-resize";
      packageName = "@jimp/plugin-resize";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-resize/-/plugin-resize-0.16.13.tgz";
        sha512 = "qoqtN8LDknm3fJm9nuPygJv30O3vGhSBD2TxrsCnhtOsxKAqVPJtFVdGd/qVuZ8nqQANQmTlfqTiK9mVWQ7MiQ==";
      };
    };
    "@jimp/plugin-rotate-0.16.13" = {
      name = "_at_jimp_slash_plugin-rotate";
      packageName = "@jimp/plugin-rotate";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-rotate/-/plugin-rotate-0.16.13.tgz";
        sha512 = "Ev+Jjmj1nHYw897z9C3R9dYsPv7S2/nxdgfFb/h8hOwK0Ovd1k/+yYS46A0uj/JCKK0pQk8wOslYBkPwdnLorw==";
      };
    };
    "@jimp/plugin-scale-0.16.13" = {
      name = "_at_jimp_slash_plugin-scale";
      packageName = "@jimp/plugin-scale";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-scale/-/plugin-scale-0.16.13.tgz";
        sha512 = "05POQaEJVucjTiSGMoH68ZiELc7QqpIpuQlZ2JBbhCV+WCbPFUBcGSmE7w4Jd0E2GvCho/NoMODLwgcVGQA97A==";
      };
    };
    "@jimp/plugin-shadow-0.16.13" = {
      name = "_at_jimp_slash_plugin-shadow";
      packageName = "@jimp/plugin-shadow";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-shadow/-/plugin-shadow-0.16.13.tgz";
        sha512 = "nmu5VSZ9hsB1JchTKhnnCY+paRBnwzSyK5fhkhtQHHoFD5ArBQ/5wU8y6tCr7k/GQhhGq1OrixsECeMjPoc8Zw==";
      };
    };
    "@jimp/plugin-threshold-0.16.13" = {
      name = "_at_jimp_slash_plugin-threshold";
      packageName = "@jimp/plugin-threshold";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugin-threshold/-/plugin-threshold-0.16.13.tgz";
        sha512 = "+3zArBH0OE3Rhjm4HyAokMsZlIq5gpQec33CncyoSwxtRBM2WAhUVmCUKuBo+Lr/2/4ISoY4BWpHKhMLDix6cA==";
      };
    };
    "@jimp/plugins-0.16.13" = {
      name = "_at_jimp_slash_plugins";
      packageName = "@jimp/plugins";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/plugins/-/plugins-0.16.13.tgz";
        sha512 = "CJLdqODEhEVs4MgWCxpWL5l95sCBlkuSLz65cxEm56X5akIsn4LOlwnKoSEZioYcZUBvHhCheH67AyPTudfnQQ==";
      };
    };
    "@jimp/png-0.16.13" = {
      name = "_at_jimp_slash_png";
      packageName = "@jimp/png";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/png/-/png-0.16.13.tgz";
        sha512 = "8cGqINvbWJf1G0Her9zbq9I80roEX0A+U45xFby3tDWfzn+Zz8XKDF1Nv9VUwVx0N3zpcG1RPs9hfheG4Cq2kg==";
      };
    };
    "@jimp/tiff-0.16.13" = {
      name = "_at_jimp_slash_tiff";
      packageName = "@jimp/tiff";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/tiff/-/tiff-0.16.13.tgz";
        sha512 = "oJY8d9u95SwW00VPHuCNxPap6Q1+E/xM5QThb9Hu+P6EGuu6lIeLaNBMmFZyblwFbwrH+WBOZlvIzDhi4Dm/6Q==";
      };
    };
    "@jimp/types-0.16.13" = {
      name = "_at_jimp_slash_types";
      packageName = "@jimp/types";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/types/-/types-0.16.13.tgz";
        sha512 = "mC0yVNUobFDjoYLg4hoUwzMKgNlxynzwt3cDXzumGvRJ7Kb8qQGOWJQjQFo5OxmGExqzPphkirdbBF88RVLBCg==";
      };
    };
    "@jimp/utils-0.16.13" = {
      name = "_at_jimp_slash_utils";
      packageName = "@jimp/utils";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jimp/utils/-/utils-0.16.13.tgz";
        sha512 = "VyCpkZzFTHXtKgVO35iKN0sYR10psGpV6SkcSeV4oF7eSYlR8Bl6aQLCzVeFjvESF7mxTmIiI3/XrMobVrtxDA==";
      };
    };
    "@resvg/resvg-js-2.6.2" = {
      name = "_at_resvg_slash_resvg-js";
      packageName = "@resvg/resvg-js";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@resvg/resvg-js/-/resvg-js-2.6.2.tgz";
        sha512 = "xBaJish5OeGmniDj9cW5PRa/PtmuVU3ziqrbr5xJj901ZDN4TosrVaNZpEiLZAxdfnhAe7uQ7QFWfjPe9d9K2Q==";
      };
    };
    "@resvg/resvg-js-darwin-arm64-2.6.2" = {
      name = "_at_resvg_slash_resvg-js-darwin-arm64";
      packageName = "@resvg/resvg-js-darwin-arm64";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@resvg/resvg-js-darwin-arm64/-/resvg-js-darwin-arm64-2.6.2.tgz";
        sha512 = "nmok2LnAd6nLUKI16aEB9ydMC6Lidiiq2m1nEBDR1LaaP7FGs4AJ90qDraxX+CWlVuRlvNjyYJTNv8qFjtL9+A==";
      };
    };
    "@resvg/resvg-js-linux-x64-gnu-2.6.2" = {
      name = "_at_resvg_slash_resvg-js-linux-x64-gnu";
      packageName = "@resvg/resvg-js-linux-x64-gnu";
      version = "2.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@resvg/resvg-js-linux-x64-gnu/-/resvg-js-linux-x64-gnu-2.6.2.tgz";
        sha512 = "IVUe+ckIerA7xMZ50duAZzwf1U7khQe2E0QpUxu5MBJNao5RqC0zwV/Zm965vw6D3gGFUl7j4m+oJjubBVoftw==";
      };
    };
    "@tokenizer/token-0.3.0" = {
      name = "_at_tokenizer_slash_token";
      packageName = "@tokenizer/token";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tokenizer/token/-/token-0.3.0.tgz";
        sha512 = "OvjF+z51L3ov0OyAU0duzsYuvO01PH7x4t6DJx+guahgTnBHkhJdG7soQeTSFLWN3efnHyibZ4Z8l2EuWwJN3A==";
      };
    };
    "@types/node-16.9.1" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "16.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-16.9.1.tgz";
        sha512 = "QpLcX9ZSsq3YYUUnD3nFDY8H7wctAhQj/TFKL8Ya8v5fMm3CFXxo8zStsLAl780ltoYoo1WvKUVGBQK+1ifr7g==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "ansi-regex-5.0.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-5.0.1.tgz";
        sha512 = "quJQXlTSUGL2LH9SUXo8VwsY4soanhgo6LNSm84E1LBcE8s3O0wpdiRzyR9z/ZZJMlMWv37qOOb9pdJlMUEKFQ==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "ansi-styles-4.3.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.3.0.tgz";
        sha512 = "zbB9rCJAT1rbjiVDb2hqKFHNYLxgtk8NURxZ3IZwD3F6NtxbXZQCnnSi1Lkx+IDohdPlFp222wVALIheZJQSEg==";
      };
    };
    "any-base-1.1.0" = {
      name = "any-base";
      packageName = "any-base";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/any-base/-/any-base-1.1.0.tgz";
        sha512 = "uMgjozySS8adZZYePpaWs8cxB9/kdzmpX6SgJZ+wbz1K5eYk5QMYDVJaZKhxyIHUdnnJkfR7SVgStgH7LkGUyg==";
      };
    };
    "array-back-3.1.0" = {
      name = "array-back";
      packageName = "array-back";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-3.1.0.tgz";
        sha512 = "TkuxA4UCOvxuDK6NZYXCalszEzj+TLszyASooky+i742l9TqsOdYCMJJupxRic61hwquNtppB3hgcuq9SVSH1Q==";
      };
    };
    "array-back-4.0.2" = {
      name = "array-back";
      packageName = "array-back";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-back/-/array-back-4.0.2.tgz";
        sha512 = "NbdMezxqf94cnNfWLL7V/im0Ub+Anbb0IoZhvzie8+4HJ4nMQuzHuy49FkGYCJK2yAloZ3meiB6AVMClbrI1vg==";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "base64-js-1.5.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.5.1.tgz";
        sha512 = "AKpaYlHn8t4SVbOHCy+b5+KKgvR4vrsD8vbvrbiQJps7fKDTkjkDry6ji0rUJjC0kzbNePLwzxq8iypo41qeWA==";
      };
    };
    "bit-field-1.9.0" = {
      name = "bit-field";
      packageName = "bit-field";
      version = "1.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bit-field/-/bit-field-1.9.0.tgz";
        sha512 = "/rVbn/yK2UBwfrlwUnNFM/MtYC5zsX+5fq8kC4J9uAPPVFWJW332TFjFlD9qMeWxwtHR014Rg5JyrLbSI9Vrlw==";
      };
    };
    "bmp-js-0.1.0" = {
      name = "bmp-js";
      packageName = "bmp-js";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bmp-js/-/bmp-js-0.1.0.tgz";
        sha512 = "vHdS19CnY3hwiNdkaqk93DvjVLfbEcI8mys4UjuWrlX1haDmroo8o4xCzh4wD6DGV6HxRCyauwhHRqMTfERtjw==";
      };
    };
    "btoa-1.2.1" = {
      name = "btoa";
      packageName = "btoa";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/btoa/-/btoa-1.2.1.tgz";
        sha512 = "SB4/MIGlsiVkMcHmT+pSmIPoNDoHg+7cMzmt3Uxt628MTz2487DKSqK/fuhFBrkuqrYv5UCEnACpF4dTFNKc/g==";
      };
    };
    "buffer-5.7.1" = {
      name = "buffer";
      packageName = "buffer";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-5.7.1.tgz";
        sha512 = "EHcyIPBQ4BSGlvjB16k5KgAJ27CIsHY/2JBmCRReo48y9rQ3MaUzWX3KVlBa4U7MyX02HdVj0K7C3WaB3ju7FQ==";
      };
    };
    "buffer-6.0.3" = {
      name = "buffer";
      packageName = "buffer";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer/-/buffer-6.0.3.tgz";
        sha512 = "FTiCpNxtwiZZHEZbcbTIcZjERVICn9yq/pDFkTl95/AxzD1naBctN7YO68riM/gLSDY7sdrMby8hofADYuuqOA==";
      };
    };
    "buffer-equal-0.0.1" = {
      name = "buffer-equal";
      packageName = "buffer-equal";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal/-/buffer-equal-0.0.1.tgz";
        sha512 = "RgSV6InVQ9ODPdLWJ5UAqBqJBOg370Nz6ZQtRzpt6nUjc8v0St97uJ4PYC6NztqIScrAXafKM3mZPMygSe1ggA==";
      };
    };
    "bytefield-svg-1.10.0" = {
      name = "bytefield-svg";
      packageName = "bytefield-svg";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytefield-svg/-/bytefield-svg-1.10.0.tgz";
        sha512 = "ftT5AqRr7kxNyu/+NSciRvayoOKB/1NyvOgFqohJDq8P8Tq5NWnmlYsMMYTy6/fpXbNFCIUnEOstzoloMUuTPg==";
      };
    };
    "centra-2.7.0" = {
      name = "centra";
      packageName = "centra";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/centra/-/centra-2.7.0.tgz";
        sha512 = "PbFMgMSrmgx6uxCdm57RUos9Tc3fclMvhLSATYN39XsDV29B89zZ3KA89jmY0vwSGazyU+uerqwa6t+KaodPcg==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "cliui-8.0.1" = {
      name = "cliui";
      packageName = "cliui";
      version = "8.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cliui/-/cliui-8.0.1.tgz";
        sha512 = "BSeNnyus75C4//NQ9gQt1/csTXyo/8Sb+afLAkzAptFuMsod9HFokGNudZpi/oQV73hnVK+sR+5PVRMd+Dr7YQ==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "command-line-args-5.2.1" = {
      name = "command-line-args";
      packageName = "command-line-args";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-args/-/command-line-args-5.2.1.tgz";
        sha512 = "H4UfQhZyakIjC74I9d34fGYDwk3XpSr17QhEd0Q3I9Xq1CETHo4Hcuo87WyWHpAF1aSLjLRf5lD9ZGX2qStUvg==";
      };
    };
    "command-line-usage-6.1.3" = {
      name = "command-line-usage";
      packageName = "command-line-usage";
      version = "6.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/command-line-usage/-/command-line-usage-6.1.3.tgz";
        sha512 = "sH5ZSPr+7UStsloltmDh7Ce5fb8XPlHyoPzTpyyMuYCtervL65+ubVZ6Q61cFtFl62UyJlc8/JwERRbAFPUqgw==";
      };
    };
    "deep-extend-0.6.0" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.6.0.tgz";
        sha512 = "LOHxIOaPYdHlJRtCQfDIVZtfw/ufM8+rVj649RIHzcm/vGwQRXFt6OPqIFWsm2XEMrNIEtWR64sY1LEKD2vAOA==";
      };
    };
    "dom-walk-0.1.2" = {
      name = "dom-walk";
      packageName = "dom-walk";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-walk/-/dom-walk-0.1.2.tgz";
        sha512 = "6QvTW9mrGeIegrFXdtQi9pk7O/nSK6lSdXW2eqUspN5LWD7UTji2Fqw5V2YLjBpHEoU9Xl/eUWNpDeZvoyOv2w==";
      };
    };
    "emoji-regex-8.0.0" = {
      name = "emoji-regex";
      packageName = "emoji-regex";
      version = "8.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz";
        sha512 = "MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==";
      };
    };
    "escalade-3.2.0" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.2.0.tgz";
        sha512 = "WUj2qlxaQtO4g6Pq5c29GTcWGDyd8itL8zTlipgECz3JesAiiOKotd8JU6otB3PACgG6xkJUyVhboMS+bje/jA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "estraverse-5.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-5.3.0.tgz";
        sha512 = "MMdARuVEQziNTeJD8DgMqmhwR11BRQ/cBP+pLtYdSTnf3MIO8fFeiINEbX36ZdNlfU/7A9f3gUw49B3oQsvwBA==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "events-3.3.0" = {
      name = "events";
      packageName = "events";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/events/-/events-3.3.0.tgz";
        sha512 = "mQw+2fkQbALzQ7V0MY0IqdnXNOeTtP4r0lN9z7AAawCXgqea7bDii20AYrIBrFd/Hx0M2Ocz6S111CaFkUcb0Q==";
      };
    };
    "exif-parser-0.1.12" = {
      name = "exif-parser";
      packageName = "exif-parser";
      version = "0.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/exif-parser/-/exif-parser-0.1.12.tgz";
        sha512 = "c2bQfLNbMzLPmzQuOr8fy0csy84WmwnER81W88DzTp9CYNPJ6yzOj2EZAh9pywYpqHnshVLHQJ8WzldAyfY+Iw==";
      };
    };
    "file-type-16.5.4" = {
      name = "file-type";
      packageName = "file-type";
      version = "16.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-type/-/file-type-16.5.4.tgz";
        sha512 = "/yFHK0aGjFEgDJjEKP0pWCplsPFPhwyfwevf/pVxiN0tmE4L9LmwWxWukdJSHdoCli4VgQLehjJtwQBnqmsKcw==";
      };
    };
    "find-replace-3.0.0" = {
      name = "find-replace";
      packageName = "find-replace";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-replace/-/find-replace-3.0.0.tgz";
        sha512 = "6Tb2myMioCAgv5kfvP5/PkZZ/ntTpVK39fHY7WkWBgvbeE+VHd/tZuZ4mrC+bxh4cfOZeYKVPaJIZtZXV7GNCQ==";
      };
    };
    "follow-redirects-1.15.9" = {
      name = "follow-redirects";
      packageName = "follow-redirects";
      version = "1.15.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/follow-redirects/-/follow-redirects-1.15.9.tgz";
        sha512 = "gew4GsXizNgdoRyqmyfMHyAmXsZDk6mHkSxZFCzW9gwlbtOW44CDtYavM+y+72qD/Vq2l550kMF52DT8fOLJqQ==";
      };
    };
    "fs-extra-11.3.0" = {
      name = "fs-extra";
      packageName = "fs-extra";
      version = "11.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-extra/-/fs-extra-11.3.0.tgz";
        sha512 = "Z4XaCL6dUDHfP/jT25jJKMmtxvuwbkrD1vNSMFlo9lNLY2c5FHYSQgHPRZUjAB26TpDEoW9HCOgplrdbaPV/ew==";
      };
    };
    "get-caller-file-2.0.5" = {
      name = "get-caller-file";
      packageName = "get-caller-file";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-caller-file/-/get-caller-file-2.0.5.tgz";
        sha512 = "DyFP3BM/3YHTQOCUL/w0OZHR0lpKeGrxotcHWcqNEdnltqFwXVfhEBQ94eIo34AfQpo0rGki4cyIiftY06h2Fg==";
      };
    };
    "gifwrap-0.9.4" = {
      name = "gifwrap";
      packageName = "gifwrap";
      version = "0.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gifwrap/-/gifwrap-0.9.4.tgz";
        sha512 = "MDMwbhASQuVeD4JKd1fKgNgCRL3fGqMM4WaqpNhWO0JiMOAjbQdumbs4BbBZEy9/M00EHEjKN3HieVhCUlwjeQ==";
      };
    };
    "global-4.4.0" = {
      name = "global";
      packageName = "global";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/global/-/global-4.4.0.tgz";
        sha512 = "wv/LAoHdRE3BeTGz53FAamhGlPLhlssK45usmGFThIi4XqnBmjKQ16u+RNbP7WvigRZDxUsM0J3gcQ5yicaL0w==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "ieee754-1.2.1" = {
      name = "ieee754";
      packageName = "ieee754";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ieee754/-/ieee754-1.2.1.tgz";
        sha512 = "dcyqhDvX1C46lXZcVqCpK+FtMRQVdIMN6/Df5js2zouUsqG7I6sFxitIC+7KYK29KdXOLHdu9zL4sFnoVQnqaA==";
      };
    };
    "image-q-4.0.0" = {
      name = "image-q";
      packageName = "image-q";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/image-q/-/image-q-4.0.0.tgz";
        sha512 = "PfJGVgIfKQJuq3s0tTDOKtztksibuUEbJQIYT3by6wctQo+Rdlh7ef4evJ5NCdxY4CfMbvFkocEwbl4BF8RlJw==";
      };
    };
    "is-fullwidth-code-point-3.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-3.0.0.tgz";
        sha512 = "zymm5+u+sCsSWyD9qNaejV3DFvhCKclKdizYaJUuHA83RLjb7nSuGnddCHGv0hk+KY7BMAlsWeK4Ueg6EV6XQg==";
      };
    };
    "is-function-1.0.2" = {
      name = "is-function";
      packageName = "is-function";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-function/-/is-function-1.0.2.tgz";
        sha512 = "lw7DUp0aWXYg+CBCN+JKkcE0Q2RayZnSvnZBlwgxHBQhqt5pZNVy4Ri7H9GmmXkdu7LUthszM+Tor1u/2iBcpQ==";
      };
    };
    "jimp-0.16.13" = {
      name = "jimp";
      packageName = "jimp";
      version = "0.16.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/jimp/-/jimp-0.16.13.tgz";
        sha512 = "Bxz8q7V4rnCky9A0ktTNGA9SkNFVWRHodddI/DaAWZJzF7sVUlFYKQ60y9JGqrKpi48ECA/TnfMzzc5C70VByA==";
      };
    };
    "jpeg-js-0.4.4" = {
      name = "jpeg-js";
      packageName = "jpeg-js";
      version = "0.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/jpeg-js/-/jpeg-js-0.4.4.tgz";
        sha512 = "WZzeDOEtTOBK4Mdsar0IqEU5sMr3vSV2RqkAIzUEV2BHnUfKGyswWFPFwK5EeDo93K3FohSHbLAjj0s1Wzd+dg==";
      };
    };
    "json5-2.2.3" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.3.tgz";
        sha512 = "XmOWe7eyHYH14cLdVPoyg+GOH3rYX++KpzrylJwSW98t3Nk+U8XOl8FWKOgwtzdb8lXGf6zYwDUzeHMWfxasyg==";
      };
    };
    "jsonfile-6.1.0" = {
      name = "jsonfile";
      packageName = "jsonfile";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonfile/-/jsonfile-6.1.0.tgz";
        sha512 = "5dgndWOriYSm5cnYaJNhalLNDKOqFwyDB/rr1E9ZsGciGvKPs8R2xYGCacuf3z6K1YKDz182fd+fY3cn3pMqXQ==";
      };
    };
    "load-bmfont-1.4.2" = {
      name = "load-bmfont";
      packageName = "load-bmfont";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/load-bmfont/-/load-bmfont-1.4.2.tgz";
        sha512 = "qElWkmjW9Oq1F9EI5Gt7aD9zcdHb9spJCW1L/dmPf7KzCCEJxq8nhHz5eCgI9aMf7vrG/wyaCqdsI+Iy9ZTlog==";
      };
    };
    "lodash.camelcase-4.3.0" = {
      name = "lodash.camelcase";
      packageName = "lodash.camelcase";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.camelcase/-/lodash.camelcase-4.3.0.tgz";
        sha512 = "TwuEnCnxbc3rAvhf/LbG7tJUDzhqXyFnv3dtzLOPgCG/hODL7WFnsbwktkD7yUV0RrreP/l1PALq/YSg6VvjlA==";
      };
    };
    "logidrom-0.3.1" = {
      name = "logidrom";
      packageName = "logidrom";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/logidrom/-/logidrom-0.3.1.tgz";
        sha512 = "B1Rjay3Ye/JcythUjMt+KLiLIwOjnMJN1M5BRbDgNMsJhmn7yApbx6n1rw7cT3Fi/NA77HDM+y3y1nXvKQVB9Q==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "min-document-2.19.0" = {
      name = "min-document";
      packageName = "min-document";
      version = "2.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/min-document/-/min-document-2.19.0.tgz";
        sha512 = "9Wy1B3m3f66bPPmU5hdA4DR4PB2OfDU/+GS3yAB7IQozE3tqXaVv2zOjgla7MEGSRv95+ILmOuvhLkOK6wJtCQ==";
      };
    };
    "minimist-1.2.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.8.tgz";
        sha512 = "2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==";
      };
    };
    "mkdirp-0.5.6" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.6.tgz";
        sha512 = "FP+p8RB8OWpF3YZBCrP5gtADmtXApB5AMLn+vdyA+PyxCjrCs00mjyUozssO33cwDeT3wNGdLxJ5M//YqtHAJw==";
      };
    };
    "omggif-1.0.10" = {
      name = "omggif";
      packageName = "omggif";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/omggif/-/omggif-1.0.10.tgz";
        sha512 = "LMJTtvgc/nugXj0Vcrrs68Mn2D1r0zf630VNtqtpI1FEO7e+O9FP4gqs9AcnBaSEeoHIPm28u6qgPR0oyEpGSw==";
      };
    };
    "onml-2.1.0" = {
      name = "onml";
      packageName = "onml";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/onml/-/onml-2.1.0.tgz";
        sha512 = "fvaSZRzprpwLFge/mcwE0CItfniNisVNamDdMK1FQUjh4ArQZ8ZWSkDaJbZc3XaANKZHq0xIa8NJpZ2HSe3oXA==";
      };
    };
    "pako-1.0.11" = {
      name = "pako";
      packageName = "pako";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pako/-/pako-1.0.11.tgz";
        sha512 = "4hLB8Py4zZce5s4yd9XzopqwVv/yGNhV1Bl8NTmCq1763HeK2+EwVTv+leGeL13Dnh2wfbqowVPXCIO0z4taYw==";
      };
    };
    "parse-bmfont-ascii-1.0.6" = {
      name = "parse-bmfont-ascii";
      packageName = "parse-bmfont-ascii";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-ascii/-/parse-bmfont-ascii-1.0.6.tgz";
        sha512 = "U4RrVsUFCleIOBsIGYOMKjn9PavsGOXxbvYGtMOEfnId0SVNsgehXh1DxUdVPLoxd5mvcEtvmKs2Mmf0Mpa1ZA==";
      };
    };
    "parse-bmfont-binary-1.0.6" = {
      name = "parse-bmfont-binary";
      packageName = "parse-bmfont-binary";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-binary/-/parse-bmfont-binary-1.0.6.tgz";
        sha512 = "GxmsRea0wdGdYthjuUeWTMWPqm2+FAd4GI8vCvhgJsFnoGhTrLhXDDupwTo7rXVAgaLIGoVHDZS9p/5XbSqeWA==";
      };
    };
    "parse-bmfont-xml-1.1.6" = {
      name = "parse-bmfont-xml";
      packageName = "parse-bmfont-xml";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-bmfont-xml/-/parse-bmfont-xml-1.1.6.tgz";
        sha512 = "0cEliVMZEhrFDwMh4SxIyVJpqYoOWDJ9P895tFuS+XuNzI5UBmBk5U5O4KuJdTnZpSBI4LFA2+ZiJaiwfSwlMA==";
      };
    };
    "parse-headers-2.0.5" = {
      name = "parse-headers";
      packageName = "parse-headers";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-headers/-/parse-headers-2.0.5.tgz";
        sha512 = "ft3iAoLOB/MlwbNXgzy43SWGP6sQki2jQvAyBg/zDFAgr9bfNWZIUj42Kw2eJIl8kEi4PbgE6U1Zau/HwI75HA==";
      };
    };
    "peek-readable-4.1.0" = {
      name = "peek-readable";
      packageName = "peek-readable";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/peek-readable/-/peek-readable-4.1.0.tgz";
        sha512 = "ZI3LnwUv5nOGbQzD9c2iDG6toheuXSZP5esSHBjopsXH4dg19soufvpUGA3uohi5anFtGb2lhAVdHzH6R/Evvg==";
      };
    };
    "phin-2.9.3" = {
      name = "phin";
      packageName = "phin";
      version = "2.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/phin/-/phin-2.9.3.tgz";
        sha512 = "CzFr90qM24ju5f88quFC/6qohjC144rehe5n6DH900lgXmUe86+xCKc10ev56gRKC4/BkHUoG4uSiQgBiIXwDA==";
      };
    };
    "phin-3.7.1" = {
      name = "phin";
      packageName = "phin";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/phin/-/phin-3.7.1.tgz";
        sha512 = "GEazpTWwTZaEQ9RhL7Nyz0WwqilbqgLahDM3D0hxWwmVDI52nXEybHqiN6/elwpkJBhcuj+WbBu+QfT0uhPGfQ==";
      };
    };
    "pixelmatch-4.0.2" = {
      name = "pixelmatch";
      packageName = "pixelmatch";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pixelmatch/-/pixelmatch-4.0.2.tgz";
        sha512 = "J8B6xqiO37sU/gkcMglv6h5Jbd9xNER7aHzpfRdNmV4IbQBzBpe4l9XmbG+xPF/znacgu2jfEw+wHffaq/YkXA==";
      };
    };
    "pngjs-3.4.0" = {
      name = "pngjs";
      packageName = "pngjs";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pngjs/-/pngjs-3.4.0.tgz";
        sha512 = "NCrCHhWmnQklfH4MtJMRjZ2a8c80qXeMlQMv2uVp9ISJMTt562SbGd6n2oq0PaPgKm7Z6pL9E2UlLIhC+SHL3w==";
      };
    };
    "process-0.11.10" = {
      name = "process";
      packageName = "process";
      version = "0.11.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/process/-/process-0.11.10.tgz";
        sha512 = "cdGef/drWFoydD1JsMzuFf8100nZl+GT+yacc2bEced5f9Rjk4z+WtFUTBu9PhOi9j/jfmBPu0mMEY4wIdAF8A==";
      };
    };
    "readable-stream-4.7.0" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "4.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-4.7.0.tgz";
        sha512 = "oIGGmcpTLwPga8Bn6/Z75SVaH1z5dUut2ibSyAMVhmUggWpmDn2dapB0n7f8nwaSiRtepAsfJyfXIO5DCVAODg==";
      };
    };
    "readable-web-to-node-stream-3.0.4" = {
      name = "readable-web-to-node-stream";
      packageName = "readable-web-to-node-stream";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-web-to-node-stream/-/readable-web-to-node-stream-3.0.4.tgz";
        sha512 = "9nX56alTf5bwXQ3ZDipHJhusu9NTQJ/CVPtb/XHAJCXihZeitfJvIRS4GqQ/mfIoOE3IelHMrpayVrosdHBuLw==";
      };
    };
    "reduce-flatten-2.0.0" = {
      name = "reduce-flatten";
      packageName = "reduce-flatten";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reduce-flatten/-/reduce-flatten-2.0.0.tgz";
        sha512 = "EJ4UNY/U1t2P/2k6oqotuX2Cc3T6nxJwsM0N0asT7dhrtH1ltUxDn4NalSYmPE2rCkVpcf/X6R0wDwcFpzhd4w==";
      };
    };
    "regenerator-runtime-0.13.11" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz";
        sha512 = "kY1AZVr2Ra+t+piVaJ4gxaFaReZVH40AKNo7UCX6W+dEwBo/2oZJzqfuN1qLq1oL45o56cPaTXELwrTh8Fpggg==";
      };
    };
    "regenerator-runtime-0.14.1" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.14.1.tgz";
        sha512 = "dYnhHh0nJoMfnkZs6GmmhFknAGRrLznOu5nc9ML+EJxGvrx6H7teuevqVqCuPcPK//3eDrrjQhehXVx9cnkGdw==";
      };
    };
    "require-directory-2.1.1" = {
      name = "require-directory";
      packageName = "require-directory";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-directory/-/require-directory-2.1.1.tgz";
        sha512 = "fGxEI7+wsG9xrvdjsrlmL22OMTTiHRwAMroiEeMgq8gzoLC/PQr7RsRDSTLUg/bZAZtF+TVIkHc6/4RIKrui+Q==";
      };
    };
    "safe-buffer-5.2.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.1.tgz";
        sha512 = "rp3So07KcdmmKbGvgaNxQSJr7bGVSVk5S9Eq1F+ppbRo70+YeaDxkw5Dd8NPN+GD6bjnYm2VuPuCXmpuYvmCXQ==";
      };
    };
    "sax-1.4.1" = {
      name = "sax";
      packageName = "sax";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.4.1.tgz";
        sha512 = "+aWOz7yVScEGoKNd4PA10LZ8sk0A/z5+nXQG5giUO5rprX9jgYsTdov9qCchZiPIZezbZH+jRut8nPodFAX4Jg==";
      };
    };
    "string-width-4.2.3" = {
      name = "string-width";
      packageName = "string-width";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-4.2.3.tgz";
        sha512 = "wKyQRQpjJ0sIp62ErSZdGsjMJWsap5oRNihHhu6G7JVO/9jIB6UyevL+tXuOqrng8j/cxKTWyWUwvSTriiZz/g==";
      };
    };
    "string_decoder-1.3.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.3.0.tgz";
        sha512 = "hkRX8U1WjJFd8LsDJ2yQ/wWWxaopEsABU1XfkM8A+j0+85JAGppt16cr1Whg6KIbb4okU6Mql6BOj+uup/wKeA==";
      };
    };
    "strip-ansi-6.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-6.0.1.tgz";
        sha512 = "Y38VPSHcqkFrCpFnQ9vuSXmquuv5oXOKpGeT6aGrr3o3Gc9AlVa6JBfUSOCnbxGGZF+/0ooI7KrPuUSztUdU5A==";
      };
    };
    "strtok3-6.3.0" = {
      name = "strtok3";
      packageName = "strtok3";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strtok3/-/strtok3-6.3.0.tgz";
        sha512 = "fZtbhtvI9I48xDSywd/somNqgUHl2L2cstmXCCif0itOf96jeW18MBSyrLuNicYQVkvpOxkZtkzujiTJ9LW5Jw==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "svg2img-1.0.0-beta.2" = {
      name = "svg2img";
      packageName = "svg2img";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/svg2img/-/svg2img-1.0.0-beta.2.tgz";
        sha512 = "Tq05Q0HTXDJZM+9ub9HCPPDbui2VavugF+/H9b1Ur9ykXbPsSUPFeXFZdDlutvDsVWZO8JjHKRdT3grpNSwwSg==";
      };
    };
    "table-layout-1.0.2" = {
      name = "table-layout";
      packageName = "table-layout";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/table-layout/-/table-layout-1.0.2.tgz";
        sha512 = "qd/R7n5rQTRFi+Zf2sk5XVVd9UQl6ZkduPFC3S7WEGJAmetDTjY3qPN50eSKzwuzEyQKy5TN2TiZdkIjos2L6A==";
      };
    };
    "timm-1.7.1" = {
      name = "timm";
      packageName = "timm";
      version = "1.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/timm/-/timm-1.7.1.tgz";
        sha512 = "IjZc9KIotudix8bMaBW6QvMuq64BrJWFs1+4V0lXwWGQZwH+LnX87doAYhem4caOEusRP9/g6jVDQmZ8XOk1nw==";
      };
    };
    "tinycolor2-1.6.0" = {
      name = "tinycolor2";
      packageName = "tinycolor2";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor2/-/tinycolor2-1.6.0.tgz";
        sha512 = "XPaBkWQJdsf3pLKJV9p4qN/S+fm2Oj8AIPo1BTUhg5oxkvm9+SVEGFdhyOz7tTdUTfvxMiAs4sp6/eZO2Ew+pw==";
      };
    };
    "token-types-4.2.1" = {
      name = "token-types";
      packageName = "token-types";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/token-types/-/token-types-4.2.1.tgz";
        sha512 = "6udB24Q737UD/SDsKAHI9FCRP7Bqc9D/MQUV02ORQg5iskjtLJlZJNdN4kKtcdtwCeWIwIHDGaUsTsCCAa8sFQ==";
      };
    };
    "tspan-0.4.0" = {
      name = "tspan";
      packageName = "tspan";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tspan/-/tspan-0.4.0.tgz";
        sha512 = "0ELL9tpLpTqLliFyQySaxgCO43buCML+j3TI4E1LuSI8wkzITGEVhZCyMvv/A+3ek9KpgALhhgnZESRLTbN+iw==";
      };
    };
    "typical-4.0.0" = {
      name = "typical";
      packageName = "typical";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-4.0.0.tgz";
        sha512 = "VAH4IvQ7BDFYglMd7BPRDfLgxZZX4O4TFcRDA6EN5X7erNJJq+McIEp8np9aVtxrCJ6qx4GTYVfOWNjcqwZgRw==";
      };
    };
    "typical-5.2.0" = {
      name = "typical";
      packageName = "typical";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/typical/-/typical-5.2.0.tgz";
        sha512 = "dvdQgNDNJo+8B2uBQoqdb11eUCE1JQXhvjC/CZtgvZseVd5TYMXnq0+vuUemXbd/Se29cTaUuPX3YIc2xgbvIg==";
      };
    };
    "universalify-2.0.1" = {
      name = "universalify";
      packageName = "universalify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universalify/-/universalify-2.0.1.tgz";
        sha512 = "gptHNQghINnc/vTGIk0SOFGFNXw7JVrlRUtConJRlvaw6DuX0wO5Jeko9sWrMBhh+PsYAZ7oXAiOnf/UKogyiw==";
      };
    };
    "utif-2.0.1" = {
      name = "utif";
      packageName = "utif";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utif/-/utif-2.0.1.tgz";
        sha512 = "Z/S1fNKCicQTf375lIP9G8Sa1H/phcysstNrrSdZKj1f9g58J4NMgb5IgiEZN9/nLMPDwF0W7hdOe9Qq2IYoLg==";
      };
    };
    "wavedrom-3.5.0" = {
      name = "wavedrom";
      packageName = "wavedrom";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wavedrom/-/wavedrom-3.5.0.tgz";
        sha512 = "UFStUpq8cbyd1KCYd9HnLpCEy1ZQtzDX72GHZTICQVZVL04JSz7+PG1DxcaSxMAEpdmW4gqGnOzs3zPrKFVO8Q==";
      };
    };
    "wavedrom-cli-3.2.0" = {
      name = "wavedrom-cli";
      packageName = "wavedrom-cli";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wavedrom-cli/-/wavedrom-cli-3.2.0.tgz";
        sha512 = "KX07T/WHnXfmoo2wvjLlx0eKeGIotB0C5GnfWVHylPfSa7BuNo0bktRCL2+zJ3g72IKc1psuRIGZIn7/soexag==";
      };
    };
    "wordwrapjs-4.0.1" = {
      name = "wordwrapjs";
      packageName = "wordwrapjs";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrapjs/-/wordwrapjs-4.0.1.tgz";
        sha512 = "kKlNACbvHrkpIw6oPeYDSmdCTu2hdMHoyXLTcUKala++lx5Y+wjJ/e474Jqv5abnVmwxw08DiTuHmw69lJGksA==";
      };
    };
    "wrap-ansi-7.0.0" = {
      name = "wrap-ansi";
      packageName = "wrap-ansi";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrap-ansi/-/wrap-ansi-7.0.0.tgz";
        sha512 = "YVGIj2kamLSTxw6NsZjoBxfSwsn0ycdesmc4p+Q21c5zPuZ1pl+NfxVdxPtdHvmNVOQ6XSYG4AUtyt/Fi7D16Q==";
      };
    };
    "xhr-2.6.0" = {
      name = "xhr";
      packageName = "xhr";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xhr/-/xhr-2.6.0.tgz";
        sha512 = "/eCGLb5rxjx5e3mF1A7s+pLlR6CGyqWN91fv1JgER5mVWg1MZmlhBvy9kjcsOdRk8RrIujotWyJamfyrp+WIcA==";
      };
    };
    "xml-parse-from-string-1.0.1" = {
      name = "xml-parse-from-string";
      packageName = "xml-parse-from-string";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml-parse-from-string/-/xml-parse-from-string-1.0.1.tgz";
        sha512 = "ErcKwJTF54uRzzNMXq2X5sMIy88zJvfN2DmdoQvy7PAFJ+tPRU6ydWuOKNMyfmOjdyBQTFREi60s0Y0SyI0G0g==";
      };
    };
    "xml2js-0.5.0" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.5.0.tgz";
        sha512 = "drPFnkQJik/O+uPKpqSgr22mpuFHqKdbS835iAQrUC73L2F5WkboIRd63ai/2Yg6I1jzifPFKH2NTK+cfglkIA==";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "y18n-5.0.8" = {
      name = "y18n";
      packageName = "y18n";
      version = "5.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/y18n/-/y18n-5.0.8.tgz";
        sha512 = "0pfFzegeDWJHJIAmTLRP2DwHjdF5s7jo9tuztdQxAhINCdvS+3nGINqPd00AphqJR/0LhANUS6/+7SCb98YOfA==";
      };
    };
    "yargs-17.7.2" = {
      name = "yargs";
      packageName = "yargs";
      version = "17.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs/-/yargs-17.7.2.tgz";
        sha512 = "7dSzzRQ++CKnNI/krKnYRV7JKKPUXMEh61soaHKg9mrWEhzFWhFnxPxGl+69cD1Ou63C13NUPCnmIcrvqCuM6w==";
      };
    };
    "yargs-parser-21.1.1" = {
      name = "yargs-parser";
      packageName = "yargs-parser";
      version = "21.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yargs-parser/-/yargs-parser-21.1.1.tgz";
        sha512 = "tVpsJW7DdjecAiFpbIB1e3qxIQsE6NoPc5/eTdrbbIC4h0LVsWhnoa3g+m2HclBIujHzsxZ4VJVA+GUuc2/LBw==";
      };
    };
  };
  args = {
    name = "deps";
    packageName = "deps";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      (sources."@babel/runtime-7.26.9" // {
        dependencies = [
          sources."regenerator-runtime-0.14.1"
        ];
      })
      sources."@jimp/bmp-0.16.13"
      sources."@jimp/core-0.16.13"
      sources."@jimp/custom-0.16.13"
      sources."@jimp/gif-0.16.13"
      sources."@jimp/jpeg-0.16.13"
      sources."@jimp/plugin-blit-0.16.13"
      sources."@jimp/plugin-blur-0.16.13"
      sources."@jimp/plugin-circle-0.16.13"
      sources."@jimp/plugin-color-0.16.13"
      sources."@jimp/plugin-contain-0.16.13"
      sources."@jimp/plugin-cover-0.16.13"
      sources."@jimp/plugin-crop-0.16.13"
      sources."@jimp/plugin-displace-0.16.13"
      sources."@jimp/plugin-dither-0.16.13"
      sources."@jimp/plugin-fisheye-0.16.13"
      sources."@jimp/plugin-flip-0.16.13"
      sources."@jimp/plugin-gaussian-0.16.13"
      sources."@jimp/plugin-invert-0.16.13"
      sources."@jimp/plugin-mask-0.16.13"
      sources."@jimp/plugin-normalize-0.16.13"
      sources."@jimp/plugin-print-0.16.13"
      sources."@jimp/plugin-resize-0.16.13"
      sources."@jimp/plugin-rotate-0.16.13"
      sources."@jimp/plugin-scale-0.16.13"
      sources."@jimp/plugin-shadow-0.16.13"
      sources."@jimp/plugin-threshold-0.16.13"
      sources."@jimp/plugins-0.16.13"
      sources."@jimp/png-0.16.13"
      sources."@jimp/tiff-0.16.13"
      sources."@jimp/types-0.16.13"
      sources."@jimp/utils-0.16.13"
      sources."@resvg/resvg-js-2.6.2"
      sources."@resvg/resvg-js-darwin-arm64-2.6.2"
      sources."@resvg/resvg-js-linux-x64-gnu-2.6.2"
      sources."@tokenizer/token-0.3.0"
      sources."@types/node-16.9.1"
      sources."abort-controller-3.0.0"
      sources."ansi-regex-5.0.1"
      sources."ansi-styles-3.2.1"
      sources."any-base-1.1.0"
      sources."array-back-3.1.0"
      sources."atob-2.1.2"
      sources."base64-js-1.5.1"
      sources."bit-field-1.9.0"
      sources."bmp-js-0.1.0"
      sources."btoa-1.2.1"
      sources."buffer-5.7.1"
      sources."buffer-equal-0.0.1"
      sources."bytefield-svg-1.10.0"
      sources."centra-2.7.0"
      sources."chalk-2.4.2"
      sources."cliui-8.0.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."command-line-args-5.2.1"
      (sources."command-line-usage-6.1.3" // {
        dependencies = [
          sources."array-back-4.0.2"
          sources."typical-5.2.0"
        ];
      })
      sources."deep-extend-0.6.0"
      sources."dom-walk-0.1.2"
      sources."emoji-regex-8.0.0"
      sources."escalade-3.2.0"
      sources."escape-string-regexp-1.0.5"
      sources."estraverse-5.3.0"
      sources."event-target-shim-5.0.1"
      sources."events-3.3.0"
      sources."exif-parser-0.1.12"
      sources."file-type-16.5.4"
      sources."find-replace-3.0.0"
      sources."follow-redirects-1.15.9"
      sources."fs-extra-11.3.0"
      sources."get-caller-file-2.0.5"
      sources."gifwrap-0.9.4"
      sources."global-4.4.0"
      sources."graceful-fs-4.2.11"
      sources."has-flag-3.0.0"
      sources."ieee754-1.2.1"
      sources."image-q-4.0.0"
      sources."is-fullwidth-code-point-3.0.0"
      sources."is-function-1.0.2"
      sources."jimp-0.16.13"
      sources."jpeg-js-0.4.4"
      sources."json5-2.2.3"
      sources."jsonfile-6.1.0"
      (sources."load-bmfont-1.4.2" // {
        dependencies = [
          sources."phin-3.7.1"
        ];
      })
      sources."lodash.camelcase-4.3.0"
      sources."logidrom-0.3.1"
      sources."mime-1.6.0"
      sources."min-document-2.19.0"
      sources."minimist-1.2.8"
      sources."mkdirp-0.5.6"
      sources."omggif-1.0.10"
      sources."onml-2.1.0"
      sources."pako-1.0.11"
      sources."parse-bmfont-ascii-1.0.6"
      sources."parse-bmfont-binary-1.0.6"
      sources."parse-bmfont-xml-1.1.6"
      sources."parse-headers-2.0.5"
      sources."peek-readable-4.1.0"
      sources."phin-2.9.3"
      sources."pixelmatch-4.0.2"
      sources."pngjs-3.4.0"
      sources."process-0.11.10"
      (sources."readable-stream-4.7.0" // {
        dependencies = [
          sources."buffer-6.0.3"
        ];
      })
      sources."readable-web-to-node-stream-3.0.4"
      sources."reduce-flatten-2.0.0"
      sources."regenerator-runtime-0.13.11"
      sources."require-directory-2.1.1"
      sources."safe-buffer-5.2.1"
      sources."sax-1.4.1"
      sources."string-width-4.2.3"
      sources."string_decoder-1.3.0"
      sources."strip-ansi-6.0.1"
      sources."strtok3-6.3.0"
      sources."supports-color-5.5.0"
      sources."svg2img-1.0.0-beta.2"
      (sources."table-layout-1.0.2" // {
        dependencies = [
          sources."array-back-4.0.2"
          sources."typical-5.2.0"
        ];
      })
      sources."timm-1.7.1"
      sources."tinycolor2-1.6.0"
      sources."token-types-4.2.1"
      sources."tspan-0.4.0"
      sources."typical-4.0.0"
      sources."universalify-2.0.1"
      sources."utif-2.0.1"
      sources."wavedrom-3.5.0"
      sources."wavedrom-cli-3.2.0"
      (sources."wordwrapjs-4.0.1" // {
        dependencies = [
          sources."typical-5.2.0"
        ];
      })
      (sources."wrap-ansi-7.0.0" // {
        dependencies = [
          sources."ansi-styles-4.3.0"
          sources."color-convert-2.0.1"
          sources."color-name-1.1.4"
        ];
      })
      sources."xhr-2.6.0"
      sources."xml-parse-from-string-1.0.1"
      sources."xml2js-0.5.0"
      sources."xmlbuilder-11.0.1"
      sources."xtend-4.0.2"
      sources."y18n-5.0.8"
      sources."yargs-17.7.2"
      sources."yargs-parser-21.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
